//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWI.InventoryAutomated.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TWI.InventoryAutomated.Resources.GlobalResource", typeof(GlobalResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access.
        /// </summary>
        public static string Access {
            get {
                return ResourceManager.GetString("Access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Sessions.
        /// </summary>
        public static string ActiveSessions {
            get {
                return ResourceManager.GetString("ActiveSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archived Sessions.
        /// </summary>
        public static string ArchivedSessions {
            get {
                return ResourceManager.GetString("ArchivedSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to Login.
        /// </summary>
        public static string ClicktoLogin {
            get {
                return ResourceManager.GetString("ClicktoLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies.
        /// </summary>
        public static string Companies {
            get {
                return ResourceManager.GetString("Companies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Details.
        /// </summary>
        public static string CompanyDetails {
            get {
                return ResourceManager.GetString("CompanyDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfirmPassword.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Count(s).
        /// </summary>
        public static string CreateIteration {
            get {
                return ResourceManager.GetString("CreateIteration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to create a new iteration ? .
        /// </summary>
        public static string CreateIterationConfirmation {
            get {
                return ResourceManager.GetString("CreateIterationConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to make this language as a default one ?.
        /// </summary>
        public static string DefaultLangConfirm {
            get {
                return ResourceManager.GetString("DefaultLangConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string DeleteBatch {
            get {
                return ResourceManager.GetString("DeleteBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Details.
        /// </summary>
        public static string DeviceDetails {
            get {
                return ResourceManager.GetString("DeviceDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Name.
        /// </summary>
        public static string DeviceName {
            get {
                return ResourceManager.GetString("DeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        public static string Devices {
            get {
                return ResourceManager.GetString("Devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email ID.
        /// </summary>
        public static string EmailID {
            get {
                return ResourceManager.GetString("EmailID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form Details.
        /// </summary>
        public static string FormDetails {
            get {
                return ResourceManager.GetString("FormDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form Name.
        /// </summary>
        public static string FormName {
            get {
                return ResourceManager.GetString("FormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forms.
        /// </summary>
        public static string Forms {
            get {
                return ResourceManager.GetString("Forms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inbound.
        /// </summary>
        public static string Inbound {
            get {
                return ResourceManager.GetString("Inbound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance.
        /// </summary>
        public static string Instance {
            get {
                return ResourceManager.GetString("Instance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance Detail.
        /// </summary>
        public static string InstanceDetail {
            get {
                return ResourceManager.GetString("InstanceDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance Name.
        /// </summary>
        public static string InstanceName {
            get {
                return ResourceManager.GetString("InstanceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance Selection.
        /// </summary>
        public static string InstanceSelection {
            get {
                return ResourceManager.GetString("InstanceSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal.
        /// </summary>
        public static string Internal {
            get {
                return ResourceManager.GetString("Internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iteration Name.
        /// </summary>
        public static string IterationName {
            get {
                return ResourceManager.GetString("IterationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Details.
        /// </summary>
        public static string LanguageDetails {
            get {
                return ResourceManager.GetString("LanguageDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Code.
        /// </summary>
        public static string LocationCode {
            get {
                return ResourceManager.GetString("LocationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAC Address.
        /// </summary>
        public static string MACAddress {
            get {
                return ResourceManager.GetString("MACAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Menu.
        /// </summary>
        public static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Details.
        /// </summary>
        public static string ModuleDetails {
            get {
                return ResourceManager.GetString("ModuleDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module ID.
        /// </summary>
        public static string ModuleID {
            get {
                return ResourceManager.GetString("ModuleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Name.
        /// </summary>
        public static string ModuleName {
            get {
                return ResourceManager.GetString("ModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules.
        /// </summary>
        public static string Modules {
            get {
                return ResourceManager.GetString("Modules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Denied, Please contact your Administrator..
        /// </summary>
        public static string MsgAccessDenied {
            get {
                return ResourceManager.GetString("MsgAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Stock Count Sheet.
        /// </summary>
        public static string MsgAdminSheetTitle {
            get {
                return ResourceManager.GetString("MsgAdminSheetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record already exists!.
        /// </summary>
        public static string MsgAlreadyExist {
            get {
                return ResourceManager.GetString("MsgAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already have active login session(s), do you wish to terminate those before proceeding?.
        /// </summary>
        public static string MsgAlreadyLoggedin {
            get {
                return ResourceManager.GetString("MsgAlreadyLoggedin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to want to pull data from navision.
        /// </summary>
        public static string MsgBatchDataPullConfirmation {
            get {
                return ResourceManager.GetString("MsgBatchDataPullConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to push selected batch data to NAV ? .
        /// </summary>
        public static string MsgBatchDataPushConfirmation {
            get {
                return ResourceManager.GetString("MsgBatchDataPushConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing Data will be overwritten if any, do you wish to continue ?.
        /// </summary>
        public static string MsgBatchExistingDataOverwrite {
            get {
                return ResourceManager.GetString("MsgBatchExistingDataOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counts &amp; Teams.
        /// </summary>
        public static string MsgBatchIterationTitle {
            get {
                return ResourceManager.GetString("MsgBatchIterationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Created Successfully.
        /// </summary>
        public static string MsgBatchSavedSuccessfully {
            get {
                return ResourceManager.GetString("MsgBatchSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch selection is mandatory to pull data from NAV ERP.
        /// </summary>
        public static string MsgBatchSelectionError {
            get {
                return ResourceManager.GetString("MsgBatchSelectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAV Data.
        /// </summary>
        public static string MsgBatchTitle {
            get {
                return ResourceManager.GetString("MsgBatchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This batch is already closed, cannot create an iteration for it.
        /// </summary>
        public static string MsgClosedBatchIterationRestriction {
            get {
                return ResourceManager.GetString("MsgClosedBatchIterationRestriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Pull Data from NAV for a Closed Batch..
        /// </summary>
        public static string MsgClosedBatchPull {
            get {
                return ResourceManager.GetString("MsgClosedBatchPull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Push Data for a Closed Batch, Kindly select a valid Batch.
        /// </summary>
        public static string MsgClosedBatchPush {
            get {
                return ResourceManager.GetString("MsgClosedBatchPush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete  the selected count?  Click &apos;Yes&apos; to Proceed Or &apos;No&apos; to Cancel.
        /// </summary>
        public static string MsgCountDeletionConfirm {
            get {
                return ResourceManager.GetString("MsgCountDeletionConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the Whse. Document no &amp; location code, no Item Lines found for this selected NAV Batch..
        /// </summary>
        public static string MsgCreateValidBatch {
            get {
                return ResourceManager.GetString("MsgCreateValidBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All existing Item Lines with be deleted from the system for the selected NAV Batch, &lt;br /&gt; click &apos;Yes&apos; to proceed Or  &apos;No&apos; to Cancel..
        /// </summary>
        public static string MsgDeleteRecord {
            get {
                return ResourceManager.GetString("MsgDeleteRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to disable this record?.
        /// </summary>
        public static string MsgDisableRecord {
            get {
                return ResourceManager.GetString("MsgDisableRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add information!.
        /// </summary>
        public static string MsgErrorwhileAdding {
            get {
                return ResourceManager.GetString("MsgErrorwhileAdding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to disable the record!.
        /// </summary>
        public static string MsgErrorwhileDisable {
            get {
                return ResourceManager.GetString("MsgErrorwhileDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update the record!.
        /// </summary>
        public static string MsgErrorWhileUpdate {
            get {
                return ResourceManager.GetString("MsgErrorWhileUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form Name is a Required Field.
        /// </summary>
        public static string MsgFormNameRequired {
            get {
                return ResourceManager.GetString("MsgFormNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Login Information.
        /// </summary>
        public static string MsgInvalidLoginInformation {
            get {
                return ResourceManager.GetString("MsgInvalidLoginInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Items for the selected batch from NAV ERP.
        /// </summary>
        public static string MsgItemsFromERP {
            get {
                return ResourceManager.GetString("MsgItemsFromERP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAC Address already exists!.
        /// </summary>
        public static string MsgMACAlreadyExist {
            get {
                return ResourceManager.GetString("MsgMACAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items of the selected batch in NAV contains Non-Zero Values in Qty (Phy. Inventory) Field, Kindly rectify in NAV. .
        /// </summary>
        public static string MsgNAVNonZeroPhyQtyMsg {
            get {
                return ResourceManager.GetString("MsgNAVNonZeroPhyQtyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records found for the selected batch.
        /// </summary>
        public static string MsgNoRecordsFound {
            get {
                return ResourceManager.GetString("MsgNoRecordsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Delete an Batch with Posted Data.
        /// </summary>
        public static string MsgOngoingBatchDeletionRestriction {
            get {
                return ResourceManager.GetString("MsgOngoingBatchDeletionRestriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock count is in progress for an existing batch, Cannot create a new batch..
        /// </summary>
        public static string MsgOngoingBatchError {
            get {
                return ResourceManager.GetString("MsgOngoingBatchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions successfully assigned.
        /// </summary>
        public static string MsgPermissionAssigned {
            get {
                return ResourceManager.GetString("MsgPermissionAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Deleted the selected Batch.
        /// </summary>
        public static string MsgSuccessfullDeletion {
            get {
                return ResourceManager.GetString("MsgSuccessfullDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully created new count..
        /// </summary>
        public static string MsgSuccessfullIterationCreation {
            get {
                return ResourceManager.GetString("MsgSuccessfullIterationCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Successfully.
        /// </summary>
        public static string MsgSuccessfullyDisabled {
            get {
                return ResourceManager.GetString("MsgSuccessfullyDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully pulled .
        /// </summary>
        public static string MsgSuccessfullyPulled {
            get {
                return ResourceManager.GetString("MsgSuccessfullyPulled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Successfully.
        /// </summary>
        public static string MsgSuccessfullySaved {
            get {
                return ResourceManager.GetString("MsgSuccessfullySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Successfully.
        /// </summary>
        public static string MsgSuccessfullyUpdated {
            get {
                return ResourceManager.GetString("MsgSuccessfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete  the selected team. Click &apos;Yes&apos; to Proceed Or &apos;No&apos; to Cancel.
        /// </summary>
        public static string MsgTeamDeletionConfirm {
            get {
                return ResourceManager.GetString("MsgTeamDeletionConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Deleted the selected team..
        /// </summary>
        public static string MsgTeamDeletionSuccessfull {
            get {
                return ResourceManager.GetString("MsgTeamDeletionSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Login!.
        /// </summary>
        public static string MsgUnabletoLogin {
            get {
                return ResourceManager.GetString("MsgUnabletoLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navision Instances.
        /// </summary>
        public static string NavisionInstances {
            get {
                return ResourceManager.GetString("NavisionInstances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAV Data - New Stock Count Batch.
        /// </summary>
        public static string NewSCTitle {
            get {
                return ResourceManager.GetString("NewSCTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OutBound.
        /// </summary>
        public static string OutBound {
            get {
                return ResourceManager.GetString("OutBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password mismatch.
        /// </summary>
        public static string Passwordmismatch {
            get {
                return ResourceManager.GetString("Passwordmismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission Details.
        /// </summary>
        public static string PermissionDetails {
            get {
                return ResourceManager.GetString("PermissionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission ID.
        /// </summary>
        public static string PermissionID {
            get {
                return ResourceManager.GetString("PermissionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission Name.
        /// </summary>
        public static string PermissionName {
            get {
                return ResourceManager.GetString("PermissionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        public static string Permissions {
            get {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed.
        /// </summary>
        public static string Proceed {
            get {
                return ResourceManager.GetString("Proceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull.
        /// </summary>
        public static string Pull {
            get {
                return ResourceManager.GetString("Pull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push.
        /// </summary>
        public static string Push {
            get {
                return ResourceManager.GetString("Push", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Devices.
        /// </summary>
        public static string RegisteredDevices {
            get {
                return ResourceManager.GetString("RegisteredDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Field.
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Count Code.
        /// </summary>
        public static string SCCode {
            get {
                return ResourceManager.GetString("SCCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Count - Item Details.
        /// </summary>
        public static string SCDetailTitle {
            get {
                return ResourceManager.GetString("SCDetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SourceFileName.
        /// </summary>
        public static string SourceFileName {
            get {
                return ResourceManager.GetString("SourceFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counts &amp; Teams.
        /// </summary>
        public static string StockBatchIterations {
            get {
                return ResourceManager.GetString("StockBatchIterations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Count.
        /// </summary>
        public static string StockCount {
            get {
                return ResourceManager.GetString("StockCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Count - Batches.
        /// </summary>
        public static string StockCountHeader {
            get {
                return ResourceManager.GetString("StockCountHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Count Sheet.
        /// </summary>
        public static string StockCountSheet {
            get {
                return ResourceManager.GetString("StockCountSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Stock Count Sheet .
        /// </summary>
        public static string StockCountSheetAdmin {
            get {
                return ResourceManager.GetString("StockCountSheetAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide valid email id.
        /// </summary>
        public static string ValidEmailID {
            get {
                return ResourceManager.GetString("ValidEmailID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web URL.
        /// </summary>
        public static string WebURL {
            get {
                return ResourceManager.GetString("WebURL", resourceCulture);
            }
        }
    }
}
