//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace TWI.InventoryAutomated.LIVEGMBHPostAdjustments {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="InventoryCount_Binding", Namespace="urn:microsoft-dynamics-schemas/codeunit/InventoryCount")]
    public partial class InventoryCount : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetAdjustmentLinesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public InventoryCount() {
            this.Url = global::TWI.InventoryAutomated.Properties.Settings.Default.TWI_InventoryAutomated_LIVEGMBHPostAdjustments_InventoryCount;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetAdjustmentLinesCompletedEventHandler GetAdjustmentLinesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/InventoryCount:GetAdjustmentLines", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/InventoryCount", ResponseElementName="GetAdjustmentLines_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/InventoryCount", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public bool GetAdjustmentLines(string itemNo, decimal quantity, string zonecode, string bincode, string lotno, [System.Xml.Serialization.XmlElementAttribute(DataType="date")] System.DateTime expirydate) {
            object[] results = this.Invoke("GetAdjustmentLines", new object[] {
                        itemNo,
                        quantity,
                        zonecode,
                        bincode,
                        lotno,
                        expirydate});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GetAdjustmentLinesAsync(string itemNo, decimal quantity, string zonecode, string bincode, string lotno, System.DateTime expirydate) {
            this.GetAdjustmentLinesAsync(itemNo, quantity, zonecode, bincode, lotno, expirydate, null);
        }
        
        /// <remarks/>
        public void GetAdjustmentLinesAsync(string itemNo, decimal quantity, string zonecode, string bincode, string lotno, System.DateTime expirydate, object userState) {
            if ((this.GetAdjustmentLinesOperationCompleted == null)) {
                this.GetAdjustmentLinesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAdjustmentLinesOperationCompleted);
            }
            this.InvokeAsync("GetAdjustmentLines", new object[] {
                        itemNo,
                        quantity,
                        zonecode,
                        bincode,
                        lotno,
                        expirydate}, this.GetAdjustmentLinesOperationCompleted, userState);
        }
        
        private void OnGetAdjustmentLinesOperationCompleted(object arg) {
            if ((this.GetAdjustmentLinesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAdjustmentLinesCompleted(this, new GetAdjustmentLinesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetAdjustmentLinesCompletedEventHandler(object sender, GetAdjustmentLinesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAdjustmentLinesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAdjustmentLinesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591