//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWI.InventoryAutomated.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://twinav01.twi.cloud:8148/TWI_NAV_DEV/WS/Theodor%20Wille%20Intertrade%20GMBH" +
            "/Page/PhysicalInvJournal")]
        public string TWI_InventoryAutomated_DEVPhyInvJournal_PhysicalInvJournal_Service {
            get {
                return ((string)(this["TWI_InventoryAutomated_DEVPhyInvJournal_PhysicalInvJournal_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://twinav01.twi.cloud:8248/TWI_NAV_TEST/WS/Theodor%20Wille%20Intertrade%20GMB" +
            "H/Page/PhysicalInvJournal")]
        public string TWI_InventoryAutomated_TESTPhyInvJournal_PhysicalInvJournal_Service {
            get {
                return ((string)(this["TWI_InventoryAutomated_TESTPhyInvJournal_PhysicalInvJournal_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://twinav01.twi.cloud:8248/TWI_NAV_TEST/WS/Theodor%20Wille%20Intertrade%20GMB" +
            "H/Page/ItemsList")]
        public string TWI_InventoryAutomated_TestItemList_ItemsList_Service {
            get {
                return ((string)(this["TWI_InventoryAutomated_TestItemList_ItemsList_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://twinav01.twi.cloud:8248/TWI_NAV_TEST/WS/Theodor%20Wille%20Intertrade%20GMB" +
            "H/Codeunit/InventoryCount")]
        public string TWI_InventoryAutomated_TESTPostAdjustments_InventoryCount {
            get {
                return ((string)(this["TWI_InventoryAutomated_TESTPostAdjustments_InventoryCount"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://twinav01.twi.cloud:8248/TWI_NAV_TEST/WS/Theodor%20Wille%20Intertrade%20GMB" +
            "H/Page/Bins")]
        public string TWI_InventoryAutomated_TESTGMBHBINS_Bins_Service {
            get {
                return ((string)(this["TWI_InventoryAutomated_TESTGMBHBINS_Bins_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://twinav01.twi.cloud:7047/twi_live/WS/Theodor%20Wille%20Intertrade%20GMBH/Pa" +
            "ge/Bins")]
        public string TWI_InventoryAutomated_LIVEGMBHBINS_Bins_Service {
            get {
                return ((string)(this["TWI_InventoryAutomated_LIVEGMBHBINS_Bins_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://twinav01.twi.cloud:7047/twi_live/WS/Theodor%20Wille%20Intertrade%20GMBH/Pa" +
            "ge/PhysicalInvJournal")]
        public string TWI_InventoryAutomated_LIVEPhyInvJournal_PhysicalInvJournal_Service {
            get {
                return ((string)(this["TWI_InventoryAutomated_LIVEPhyInvJournal_PhysicalInvJournal_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://twinav01.twi.cloud:7047/twi_live/WS/Theodor%20Wille%20Intertrade%20GMBH/Pa" +
            "ge/ItemsList")]
        public string TWI_InventoryAutomated_LiveGMBHItemList_ItemsList_Service {
            get {
                return ((string)(this["TWI_InventoryAutomated_LiveGMBHItemList_ItemsList_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://twinav01.twi.cloud:7047/twi_live/WS/Theodor%20Wille%20Intertrade%20GMBH/Co" +
            "deunit/InventoryCount")]
        public string TWI_InventoryAutomated_LIVEGMBHPostAdjustments_InventoryCount {
            get {
                return ((string)(this["TWI_InventoryAutomated_LIVEGMBHPostAdjustments_InventoryCount"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://twinav01.twi.cloud:8248/TWI_NAV_TEST/WS/Theodor%20Wille%20Intertrade%20GMB" +
            "H/Page/Users")]
        public string TWI_InventoryAutomated_TestGmbhWh_Users_Users_Service {
            get {
                return ((string)(this["TWI_InventoryAutomated_TestGmbhWh_Users_Users_Service"]));
            }
        }
    }
}
