//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWI.InventoryAutomated.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArchivedSessionLog
    {
        public int ID { get; set; }
        public Nullable<int> SessionLogID { get; set; }
        public string FormName { get; set; }
        public string ControlName { get; set; }
        public string ActivityPerformed { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Exception { get; set; }
    }
}
