//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace TWI.InventoryAutomated.LiveGMBHItemList {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ItemsList_Binding", Namespace="urn:microsoft-dynamics-schemas/page/itemslist")]
    public partial class ItemsList_Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ReadOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadByRecIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsUpdatedOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRecIdFromKeyOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ItemsList_Service() {
            this.Url = global::TWI.InventoryAutomated.Properties.Settings.Default.TWI_InventoryAutomated_LiveGMBHItemList_ItemsList_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ReadCompletedEventHandler ReadCompleted;
        
        /// <remarks/>
        public event ReadByRecIdCompletedEventHandler ReadByRecIdCompleted;
        
        /// <remarks/>
        public event ReadMultipleCompletedEventHandler ReadMultipleCompleted;
        
        /// <remarks/>
        public event IsUpdatedCompletedEventHandler IsUpdatedCompleted;
        
        /// <remarks/>
        public event GetRecIdFromKeyCompletedEventHandler GetRecIdFromKeyCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/itemslist:Read", RequestNamespace="urn:microsoft-dynamics-schemas/page/itemslist", ResponseElementName="Read_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/itemslist", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ItemsList")]
        public ItemsList Read(string No) {
            object[] results = this.Invoke("Read", new object[] {
                        No});
            return ((ItemsList)(results[0]));
        }
        
        /// <remarks/>
        public void ReadAsync(string No) {
            this.ReadAsync(No, null);
        }
        
        /// <remarks/>
        public void ReadAsync(string No, object userState) {
            if ((this.ReadOperationCompleted == null)) {
                this.ReadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadOperationCompleted);
            }
            this.InvokeAsync("Read", new object[] {
                        No}, this.ReadOperationCompleted, userState);
        }
        
        private void OnReadOperationCompleted(object arg) {
            if ((this.ReadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadCompleted(this, new ReadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/itemslist:ReadByRecId", RequestNamespace="urn:microsoft-dynamics-schemas/page/itemslist", ResponseElementName="ReadByRecId_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/itemslist", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ItemsList")]
        public ItemsList ReadByRecId(string recId) {
            object[] results = this.Invoke("ReadByRecId", new object[] {
                        recId});
            return ((ItemsList)(results[0]));
        }
        
        /// <remarks/>
        public void ReadByRecIdAsync(string recId) {
            this.ReadByRecIdAsync(recId, null);
        }
        
        /// <remarks/>
        public void ReadByRecIdAsync(string recId, object userState) {
            if ((this.ReadByRecIdOperationCompleted == null)) {
                this.ReadByRecIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadByRecIdOperationCompleted);
            }
            this.InvokeAsync("ReadByRecId", new object[] {
                        recId}, this.ReadByRecIdOperationCompleted, userState);
        }
        
        private void OnReadByRecIdOperationCompleted(object arg) {
            if ((this.ReadByRecIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadByRecIdCompleted(this, new ReadByRecIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/itemslist:ReadMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/itemslist", ResponseElementName="ReadMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/itemslist", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("ReadMultiple_Result")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ItemsList[] ReadMultiple([System.Xml.Serialization.XmlElementAttribute("filter")] ItemsList_Filter[] filter, string bookmarkKey, int setSize) {
            object[] results = this.Invoke("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize});
            return ((ItemsList[])(results[0]));
        }
        
        /// <remarks/>
        public void ReadMultipleAsync(ItemsList_Filter[] filter, string bookmarkKey, int setSize) {
            this.ReadMultipleAsync(filter, bookmarkKey, setSize, null);
        }
        
        /// <remarks/>
        public void ReadMultipleAsync(ItemsList_Filter[] filter, string bookmarkKey, int setSize, object userState) {
            if ((this.ReadMultipleOperationCompleted == null)) {
                this.ReadMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadMultipleOperationCompleted);
            }
            this.InvokeAsync("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize}, this.ReadMultipleOperationCompleted, userState);
        }
        
        private void OnReadMultipleOperationCompleted(object arg) {
            if ((this.ReadMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadMultipleCompleted(this, new ReadMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/itemslist:IsUpdated", RequestNamespace="urn:microsoft-dynamics-schemas/page/itemslist", ResponseElementName="IsUpdated_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/itemslist", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("IsUpdated_Result")]
        public bool IsUpdated(string Key) {
            object[] results = this.Invoke("IsUpdated", new object[] {
                        Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsUpdatedAsync(string Key) {
            this.IsUpdatedAsync(Key, null);
        }
        
        /// <remarks/>
        public void IsUpdatedAsync(string Key, object userState) {
            if ((this.IsUpdatedOperationCompleted == null)) {
                this.IsUpdatedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsUpdatedOperationCompleted);
            }
            this.InvokeAsync("IsUpdated", new object[] {
                        Key}, this.IsUpdatedOperationCompleted, userState);
        }
        
        private void OnIsUpdatedOperationCompleted(object arg) {
            if ((this.IsUpdatedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsUpdatedCompleted(this, new IsUpdatedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/itemslist:GetRecIdFromKey", RequestNamespace="urn:microsoft-dynamics-schemas/page/itemslist", ResponseElementName="GetRecIdFromKey_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/itemslist", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetRecIdFromKey_Result")]
        public string GetRecIdFromKey(string Key) {
            object[] results = this.Invoke("GetRecIdFromKey", new object[] {
                        Key});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetRecIdFromKeyAsync(string Key) {
            this.GetRecIdFromKeyAsync(Key, null);
        }
        
        /// <remarks/>
        public void GetRecIdFromKeyAsync(string Key, object userState) {
            if ((this.GetRecIdFromKeyOperationCompleted == null)) {
                this.GetRecIdFromKeyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRecIdFromKeyOperationCompleted);
            }
            this.InvokeAsync("GetRecIdFromKey", new object[] {
                        Key}, this.GetRecIdFromKeyOperationCompleted, userState);
        }
        
        private void OnGetRecIdFromKeyOperationCompleted(object arg) {
            if ((this.GetRecIdFromKeyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRecIdFromKeyCompleted(this, new GetRecIdFromKeyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemslist")]
    public partial class ItemsList {
        
        private string keyField;
        
        private string noField;
        
        private string descriptionField;
        
        private string description_2Field;
        
        private string tW_NSN_No_Cross_Reference_NoField;
        
        private TWI_Item_Type tWI_Item_TypeField;
        
        private bool tWI_Item_TypeFieldSpecified;
        
        private string tWI_Update_IndicatorField;
        
        private string shelf_Life_PeriodField;
        
        private Addition_Status addition_StatusField;
        
        private bool addition_StatusFieldSpecified;
        
        private string tWI_FICCodeField;
        
        private bool created_From_Nonstock_ItemField;
        
        private bool created_From_Nonstock_ItemFieldSpecified;
        
        private bool substitutes_ExistField;
        
        private bool substitutes_ExistFieldSpecified;
        
        private bool stockkeeping_Unit_ExistsField;
        
        private bool stockkeeping_Unit_ExistsFieldSpecified;
        
        private bool assembly_BOMField;
        
        private bool assembly_BOMFieldSpecified;
        
        private string production_BOM_NoField;
        
        private string routing_NoField;
        
        private string base_Unit_of_MeasureField;
        
        private string shelf_NoField;
        
        private Costing_Method costing_MethodField;
        
        private bool costing_MethodFieldSpecified;
        
        private bool cost_is_AdjustedField;
        
        private bool cost_is_AdjustedFieldSpecified;
        
        private decimal standard_CostField;
        
        private bool standard_CostFieldSpecified;
        
        private decimal tWI_Unit_PriceField;
        
        private bool tWI_Unit_PriceFieldSpecified;
        
        private decimal nAPA_Allowance_Pending_ApprovalField;
        
        private bool nAPA_Allowance_Pending_ApprovalFieldSpecified;
        
        private decimal rOUND_Unit_CostField;
        
        private bool rOUND_Unit_CostFieldSpecified;
        
        private decimal last_Direct_CostField;
        
        private bool last_Direct_CostFieldSpecified;
        
        private Price_Profit_Calculation price_Profit_CalculationField;
        
        private bool price_Profit_CalculationFieldSpecified;
        
        private decimal net_WeightField;
        
        private bool net_WeightFieldSpecified;
        
        private decimal profit_PercentField;
        
        private bool profit_PercentFieldSpecified;
        
        private decimal unit_PriceField;
        
        private bool unit_PriceFieldSpecified;
        
        private string inventory_Posting_GroupField;
        
        private string gen_Prod_Posting_GroupField;
        
        private string vAT_Prod_Posting_GroupField;
        
        private string item_Disc_GroupField;
        
        private string vendor_NoField;
        
        private string vendor_NameField;
        
        private string vendor_Item_NoField;
        
        private string tariff_NoField;
        
        private string search_DescriptionField;
        
        private decimal overhead_RateField;
        
        private bool overhead_RateFieldSpecified;
        
        private decimal indirect_Cost_PercentField;
        
        private bool indirect_Cost_PercentFieldSpecified;
        
        private string item_Category_CodeField;
        
        private string product_Group_CodeField;
        
        private bool blockedField;
        
        private bool blockedFieldSpecified;
        
        private System.DateTime last_Date_ModifiedField;
        
        private bool last_Date_ModifiedFieldSpecified;
        
        private string sales_Unit_of_MeasureField;
        
        private Replenishment_System replenishment_SystemField;
        
        private bool replenishment_SystemFieldSpecified;
        
        private string purch_Unit_of_MeasureField;
        
        private string lead_Time_CalculationField;
        
        private Manufacturing_Policy manufacturing_PolicyField;
        
        private bool manufacturing_PolicyFieldSpecified;
        
        private Flushing_Method flushing_MethodField;
        
        private bool flushing_MethodFieldSpecified;
        
        private string manufacturer_CodeField;
        
        private string brand_CodeField;
        
        private decimal inventoryField;
        
        private bool inventoryFieldSpecified;
        
        private string aktobe_StockField;
        
        private string aktau_StockField;
        
        private decimal qty_on_Purch_OrderField;
        
        private bool qty_on_Purch_OrderFieldSpecified;
        
        private decimal qty_on_Sales_OrderField;
        
        private bool qty_on_Sales_OrderFieldSpecified;
        
        private decimal outstanding_Qty_on_I_B_TOsField;
        
        private bool outstanding_Qty_on_I_B_TOsFieldSpecified;
        
        private decimal outstanding_Qty_on_O_B_TOsField;
        
        private bool outstanding_Qty_on_O_B_TOsFieldSpecified;
        
        private decimal reserved_Qty_on_InventoryField;
        
        private bool reserved_Qty_on_InventoryFieldSpecified;
        
        private decimal reserved_Qty_on_Purch_OrdersField;
        
        private bool reserved_Qty_on_Purch_OrdersFieldSpecified;
        
        private decimal reserved_Qty_on_Sales_OrdersField;
        
        private bool reserved_Qty_on_Sales_OrdersFieldSpecified;
        
        private decimal res_Qty_on_Outbound_TransferField;
        
        private bool res_Qty_on_Outbound_TransferFieldSpecified;
        
        private decimal res_Qty_on_Inbound_TransferField;
        
        private bool res_Qty_on_Inbound_TransferFieldSpecified;
        
        private bool history_at_LocationField;
        
        private bool history_at_LocationFieldSpecified;
        
        private bool purchase_blockedField;
        
        private bool purchase_blockedFieldSpecified;
        
        private Assembly_Policy assembly_PolicyField;
        
        private bool assembly_PolicyFieldSpecified;
        
        private decimal qty_SoldField;
        
        private bool qty_SoldFieldSpecified;
        
        private string item_Tracking_CodeField;
        
        private decimal gross_WeightField;
        
        private bool gross_WeightFieldSpecified;
        
        private string economic_IndicatorField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Description_2 {
            get {
                return this.description_2Field;
            }
            set {
                this.description_2Field = value;
            }
        }
        
        /// <remarks/>
        public string TW_NSN_No_Cross_Reference_No {
            get {
                return this.tW_NSN_No_Cross_Reference_NoField;
            }
            set {
                this.tW_NSN_No_Cross_Reference_NoField = value;
            }
        }
        
        /// <remarks/>
        public TWI_Item_Type TWI_Item_Type {
            get {
                return this.tWI_Item_TypeField;
            }
            set {
                this.tWI_Item_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TWI_Item_TypeSpecified {
            get {
                return this.tWI_Item_TypeFieldSpecified;
            }
            set {
                this.tWI_Item_TypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TWI_Update_Indicator>")]
        public string TWI_Update_Indicator {
            get {
                return this.tWI_Update_IndicatorField;
            }
            set {
                this.tWI_Update_IndicatorField = value;
            }
        }
        
        /// <remarks/>
        public string Shelf_Life_Period {
            get {
                return this.shelf_Life_PeriodField;
            }
            set {
                this.shelf_Life_PeriodField = value;
            }
        }
        
        /// <remarks/>
        public Addition_Status Addition_Status {
            get {
                return this.addition_StatusField;
            }
            set {
                this.addition_StatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Addition_StatusSpecified {
            get {
                return this.addition_StatusFieldSpecified;
            }
            set {
                this.addition_StatusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string TWI_FICCode {
            get {
                return this.tWI_FICCodeField;
            }
            set {
                this.tWI_FICCodeField = value;
            }
        }
        
        /// <remarks/>
        public bool Created_From_Nonstock_Item {
            get {
                return this.created_From_Nonstock_ItemField;
            }
            set {
                this.created_From_Nonstock_ItemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Created_From_Nonstock_ItemSpecified {
            get {
                return this.created_From_Nonstock_ItemFieldSpecified;
            }
            set {
                this.created_From_Nonstock_ItemFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Substitutes_Exist {
            get {
                return this.substitutes_ExistField;
            }
            set {
                this.substitutes_ExistField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Substitutes_ExistSpecified {
            get {
                return this.substitutes_ExistFieldSpecified;
            }
            set {
                this.substitutes_ExistFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Stockkeeping_Unit_Exists {
            get {
                return this.stockkeeping_Unit_ExistsField;
            }
            set {
                this.stockkeeping_Unit_ExistsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Stockkeeping_Unit_ExistsSpecified {
            get {
                return this.stockkeeping_Unit_ExistsFieldSpecified;
            }
            set {
                this.stockkeeping_Unit_ExistsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Assembly_BOM {
            get {
                return this.assembly_BOMField;
            }
            set {
                this.assembly_BOMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Assembly_BOMSpecified {
            get {
                return this.assembly_BOMFieldSpecified;
            }
            set {
                this.assembly_BOMFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Production_BOM_No {
            get {
                return this.production_BOM_NoField;
            }
            set {
                this.production_BOM_NoField = value;
            }
        }
        
        /// <remarks/>
        public string Routing_No {
            get {
                return this.routing_NoField;
            }
            set {
                this.routing_NoField = value;
            }
        }
        
        /// <remarks/>
        public string Base_Unit_of_Measure {
            get {
                return this.base_Unit_of_MeasureField;
            }
            set {
                this.base_Unit_of_MeasureField = value;
            }
        }
        
        /// <remarks/>
        public string Shelf_No {
            get {
                return this.shelf_NoField;
            }
            set {
                this.shelf_NoField = value;
            }
        }
        
        /// <remarks/>
        public Costing_Method Costing_Method {
            get {
                return this.costing_MethodField;
            }
            set {
                this.costing_MethodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Costing_MethodSpecified {
            get {
                return this.costing_MethodFieldSpecified;
            }
            set {
                this.costing_MethodFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Cost_is_Adjusted {
            get {
                return this.cost_is_AdjustedField;
            }
            set {
                this.cost_is_AdjustedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Cost_is_AdjustedSpecified {
            get {
                return this.cost_is_AdjustedFieldSpecified;
            }
            set {
                this.cost_is_AdjustedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Standard_Cost {
            get {
                return this.standard_CostField;
            }
            set {
                this.standard_CostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Standard_CostSpecified {
            get {
                return this.standard_CostFieldSpecified;
            }
            set {
                this.standard_CostFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal TWI_Unit_Price {
            get {
                return this.tWI_Unit_PriceField;
            }
            set {
                this.tWI_Unit_PriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TWI_Unit_PriceSpecified {
            get {
                return this.tWI_Unit_PriceFieldSpecified;
            }
            set {
                this.tWI_Unit_PriceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal NAPA_Allowance_Pending_Approval {
            get {
                return this.nAPA_Allowance_Pending_ApprovalField;
            }
            set {
                this.nAPA_Allowance_Pending_ApprovalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NAPA_Allowance_Pending_ApprovalSpecified {
            get {
                return this.nAPA_Allowance_Pending_ApprovalFieldSpecified;
            }
            set {
                this.nAPA_Allowance_Pending_ApprovalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal ROUND_Unit_Cost {
            get {
                return this.rOUND_Unit_CostField;
            }
            set {
                this.rOUND_Unit_CostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ROUND_Unit_CostSpecified {
            get {
                return this.rOUND_Unit_CostFieldSpecified;
            }
            set {
                this.rOUND_Unit_CostFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Last_Direct_Cost {
            get {
                return this.last_Direct_CostField;
            }
            set {
                this.last_Direct_CostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Last_Direct_CostSpecified {
            get {
                return this.last_Direct_CostFieldSpecified;
            }
            set {
                this.last_Direct_CostFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Price_Profit_Calculation Price_Profit_Calculation {
            get {
                return this.price_Profit_CalculationField;
            }
            set {
                this.price_Profit_CalculationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Price_Profit_CalculationSpecified {
            get {
                return this.price_Profit_CalculationFieldSpecified;
            }
            set {
                this.price_Profit_CalculationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Net_Weight {
            get {
                return this.net_WeightField;
            }
            set {
                this.net_WeightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Net_WeightSpecified {
            get {
                return this.net_WeightFieldSpecified;
            }
            set {
                this.net_WeightFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Profit_Percent {
            get {
                return this.profit_PercentField;
            }
            set {
                this.profit_PercentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Profit_PercentSpecified {
            get {
                return this.profit_PercentFieldSpecified;
            }
            set {
                this.profit_PercentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Unit_Price {
            get {
                return this.unit_PriceField;
            }
            set {
                this.unit_PriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Unit_PriceSpecified {
            get {
                return this.unit_PriceFieldSpecified;
            }
            set {
                this.unit_PriceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Inventory_Posting_Group {
            get {
                return this.inventory_Posting_GroupField;
            }
            set {
                this.inventory_Posting_GroupField = value;
            }
        }
        
        /// <remarks/>
        public string Gen_Prod_Posting_Group {
            get {
                return this.gen_Prod_Posting_GroupField;
            }
            set {
                this.gen_Prod_Posting_GroupField = value;
            }
        }
        
        /// <remarks/>
        public string VAT_Prod_Posting_Group {
            get {
                return this.vAT_Prod_Posting_GroupField;
            }
            set {
                this.vAT_Prod_Posting_GroupField = value;
            }
        }
        
        /// <remarks/>
        public string Item_Disc_Group {
            get {
                return this.item_Disc_GroupField;
            }
            set {
                this.item_Disc_GroupField = value;
            }
        }
        
        /// <remarks/>
        public string Vendor_No {
            get {
                return this.vendor_NoField;
            }
            set {
                this.vendor_NoField = value;
            }
        }
        
        /// <remarks/>
        public string Vendor_Name {
            get {
                return this.vendor_NameField;
            }
            set {
                this.vendor_NameField = value;
            }
        }
        
        /// <remarks/>
        public string Vendor_Item_No {
            get {
                return this.vendor_Item_NoField;
            }
            set {
                this.vendor_Item_NoField = value;
            }
        }
        
        /// <remarks/>
        public string Tariff_No {
            get {
                return this.tariff_NoField;
            }
            set {
                this.tariff_NoField = value;
            }
        }
        
        /// <remarks/>
        public string Search_Description {
            get {
                return this.search_DescriptionField;
            }
            set {
                this.search_DescriptionField = value;
            }
        }
        
        /// <remarks/>
        public decimal Overhead_Rate {
            get {
                return this.overhead_RateField;
            }
            set {
                this.overhead_RateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Overhead_RateSpecified {
            get {
                return this.overhead_RateFieldSpecified;
            }
            set {
                this.overhead_RateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Indirect_Cost_Percent {
            get {
                return this.indirect_Cost_PercentField;
            }
            set {
                this.indirect_Cost_PercentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Indirect_Cost_PercentSpecified {
            get {
                return this.indirect_Cost_PercentFieldSpecified;
            }
            set {
                this.indirect_Cost_PercentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Item_Category_Code {
            get {
                return this.item_Category_CodeField;
            }
            set {
                this.item_Category_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Product_Group_Code {
            get {
                return this.product_Group_CodeField;
            }
            set {
                this.product_Group_CodeField = value;
            }
        }
        
        /// <remarks/>
        public bool Blocked {
            get {
                return this.blockedField;
            }
            set {
                this.blockedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BlockedSpecified {
            get {
                return this.blockedFieldSpecified;
            }
            set {
                this.blockedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Last_Date_Modified {
            get {
                return this.last_Date_ModifiedField;
            }
            set {
                this.last_Date_ModifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Last_Date_ModifiedSpecified {
            get {
                return this.last_Date_ModifiedFieldSpecified;
            }
            set {
                this.last_Date_ModifiedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Sales_Unit_of_Measure {
            get {
                return this.sales_Unit_of_MeasureField;
            }
            set {
                this.sales_Unit_of_MeasureField = value;
            }
        }
        
        /// <remarks/>
        public Replenishment_System Replenishment_System {
            get {
                return this.replenishment_SystemField;
            }
            set {
                this.replenishment_SystemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Replenishment_SystemSpecified {
            get {
                return this.replenishment_SystemFieldSpecified;
            }
            set {
                this.replenishment_SystemFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Purch_Unit_of_Measure {
            get {
                return this.purch_Unit_of_MeasureField;
            }
            set {
                this.purch_Unit_of_MeasureField = value;
            }
        }
        
        /// <remarks/>
        public string Lead_Time_Calculation {
            get {
                return this.lead_Time_CalculationField;
            }
            set {
                this.lead_Time_CalculationField = value;
            }
        }
        
        /// <remarks/>
        public Manufacturing_Policy Manufacturing_Policy {
            get {
                return this.manufacturing_PolicyField;
            }
            set {
                this.manufacturing_PolicyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Manufacturing_PolicySpecified {
            get {
                return this.manufacturing_PolicyFieldSpecified;
            }
            set {
                this.manufacturing_PolicyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Flushing_Method Flushing_Method {
            get {
                return this.flushing_MethodField;
            }
            set {
                this.flushing_MethodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Flushing_MethodSpecified {
            get {
                return this.flushing_MethodFieldSpecified;
            }
            set {
                this.flushing_MethodFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Manufacturer_Code {
            get {
                return this.manufacturer_CodeField;
            }
            set {
                this.manufacturer_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Brand_Code {
            get {
                return this.brand_CodeField;
            }
            set {
                this.brand_CodeField = value;
            }
        }
        
        /// <remarks/>
        public decimal Inventory {
            get {
                return this.inventoryField;
            }
            set {
                this.inventoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InventorySpecified {
            get {
                return this.inventoryFieldSpecified;
            }
            set {
                this.inventoryFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Aktobe_Stock {
            get {
                return this.aktobe_StockField;
            }
            set {
                this.aktobe_StockField = value;
            }
        }
        
        /// <remarks/>
        public string Aktau_Stock {
            get {
                return this.aktau_StockField;
            }
            set {
                this.aktau_StockField = value;
            }
        }
        
        /// <remarks/>
        public decimal Qty_on_Purch_Order {
            get {
                return this.qty_on_Purch_OrderField;
            }
            set {
                this.qty_on_Purch_OrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Qty_on_Purch_OrderSpecified {
            get {
                return this.qty_on_Purch_OrderFieldSpecified;
            }
            set {
                this.qty_on_Purch_OrderFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Qty_on_Sales_Order {
            get {
                return this.qty_on_Sales_OrderField;
            }
            set {
                this.qty_on_Sales_OrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Qty_on_Sales_OrderSpecified {
            get {
                return this.qty_on_Sales_OrderFieldSpecified;
            }
            set {
                this.qty_on_Sales_OrderFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Outstanding_Qty_on_I_B_TO\'s")]
        public decimal Outstanding_Qty_on_I_B_TOs {
            get {
                return this.outstanding_Qty_on_I_B_TOsField;
            }
            set {
                this.outstanding_Qty_on_I_B_TOsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Outstanding_Qty_on_I_B_TOsSpecified {
            get {
                return this.outstanding_Qty_on_I_B_TOsFieldSpecified;
            }
            set {
                this.outstanding_Qty_on_I_B_TOsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Outstanding_Qty_on_O_B_TO\'s")]
        public decimal Outstanding_Qty_on_O_B_TOs {
            get {
                return this.outstanding_Qty_on_O_B_TOsField;
            }
            set {
                this.outstanding_Qty_on_O_B_TOsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Outstanding_Qty_on_O_B_TOsSpecified {
            get {
                return this.outstanding_Qty_on_O_B_TOsFieldSpecified;
            }
            set {
                this.outstanding_Qty_on_O_B_TOsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Reserved_Qty_on_Inventory {
            get {
                return this.reserved_Qty_on_InventoryField;
            }
            set {
                this.reserved_Qty_on_InventoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Reserved_Qty_on_InventorySpecified {
            get {
                return this.reserved_Qty_on_InventoryFieldSpecified;
            }
            set {
                this.reserved_Qty_on_InventoryFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Reserved_Qty_on_Purch_Orders {
            get {
                return this.reserved_Qty_on_Purch_OrdersField;
            }
            set {
                this.reserved_Qty_on_Purch_OrdersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Reserved_Qty_on_Purch_OrdersSpecified {
            get {
                return this.reserved_Qty_on_Purch_OrdersFieldSpecified;
            }
            set {
                this.reserved_Qty_on_Purch_OrdersFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Reserved_Qty_on_Sales_Orders {
            get {
                return this.reserved_Qty_on_Sales_OrdersField;
            }
            set {
                this.reserved_Qty_on_Sales_OrdersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Reserved_Qty_on_Sales_OrdersSpecified {
            get {
                return this.reserved_Qty_on_Sales_OrdersFieldSpecified;
            }
            set {
                this.reserved_Qty_on_Sales_OrdersFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Res_Qty_on_Outbound_Transfer {
            get {
                return this.res_Qty_on_Outbound_TransferField;
            }
            set {
                this.res_Qty_on_Outbound_TransferField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Res_Qty_on_Outbound_TransferSpecified {
            get {
                return this.res_Qty_on_Outbound_TransferFieldSpecified;
            }
            set {
                this.res_Qty_on_Outbound_TransferFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Res_Qty_on_Inbound_Transfer {
            get {
                return this.res_Qty_on_Inbound_TransferField;
            }
            set {
                this.res_Qty_on_Inbound_TransferField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Res_Qty_on_Inbound_TransferSpecified {
            get {
                return this.res_Qty_on_Inbound_TransferFieldSpecified;
            }
            set {
                this.res_Qty_on_Inbound_TransferFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool History_at_Location {
            get {
                return this.history_at_LocationField;
            }
            set {
                this.history_at_LocationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool History_at_LocationSpecified {
            get {
                return this.history_at_LocationFieldSpecified;
            }
            set {
                this.history_at_LocationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Purchase_blocked {
            get {
                return this.purchase_blockedField;
            }
            set {
                this.purchase_blockedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Purchase_blockedSpecified {
            get {
                return this.purchase_blockedFieldSpecified;
            }
            set {
                this.purchase_blockedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Assembly_Policy Assembly_Policy {
            get {
                return this.assembly_PolicyField;
            }
            set {
                this.assembly_PolicyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Assembly_PolicySpecified {
            get {
                return this.assembly_PolicyFieldSpecified;
            }
            set {
                this.assembly_PolicyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Qty_Sold {
            get {
                return this.qty_SoldField;
            }
            set {
                this.qty_SoldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Qty_SoldSpecified {
            get {
                return this.qty_SoldFieldSpecified;
            }
            set {
                this.qty_SoldFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Item_Tracking_Code {
            get {
                return this.item_Tracking_CodeField;
            }
            set {
                this.item_Tracking_CodeField = value;
            }
        }
        
        /// <remarks/>
        public decimal Gross_Weight {
            get {
                return this.gross_WeightField;
            }
            set {
                this.gross_WeightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Gross_WeightSpecified {
            get {
                return this.gross_WeightFieldSpecified;
            }
            set {
                this.gross_WeightFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Economic_Indicator {
            get {
                return this.economic_IndicatorField;
            }
            set {
                this.economic_IndicatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemslist")]
    public enum TWI_Item_Type {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        MPA,
        
        /// <remarks/>
        NAPA,
        
        /// <remarks/>
        Regular,
        
        /// <remarks/>
        Distribution,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemslist")]
    public enum Addition_Status {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        Not_Approved_New_Item,
        
        /// <remarks/>
        Approved_New_Item,
        
        /// <remarks/>
        Active,
        
        /// <remarks/>
        Deleted,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemslist")]
    public enum Costing_Method {
        
        /// <remarks/>
        FIFO,
        
        /// <remarks/>
        LIFO,
        
        /// <remarks/>
        Specific,
        
        /// <remarks/>
        Average,
        
        /// <remarks/>
        Standard,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemslist")]
    public enum Price_Profit_Calculation {
        
        /// <remarks/>
        Profit_x003D_Price_Cost,
        
        /// <remarks/>
        Price_x003D_Cost_x002B_Profit,
        
        /// <remarks/>
        No_Relationship,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemslist")]
    public enum Replenishment_System {
        
        /// <remarks/>
        Purchase,
        
        /// <remarks/>
        Prod_Order,
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Assembly,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemslist")]
    public enum Manufacturing_Policy {
        
        /// <remarks/>
        Make_to_Stock,
        
        /// <remarks/>
        Make_to_Order,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemslist")]
    public enum Flushing_Method {
        
        /// <remarks/>
        Manual,
        
        /// <remarks/>
        Forward,
        
        /// <remarks/>
        Backward,
        
        /// <remarks/>
        Pick__x002B__Forward,
        
        /// <remarks/>
        Pick__x002B__Backward,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemslist")]
    public enum Assembly_Policy {
        
        /// <remarks/>
        Assemble_to_Stock,
        
        /// <remarks/>
        Assemble_to_Order,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemslist")]
    public partial class ItemsList_Filter {
        
        private ItemsList_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        public ItemsList_Fields Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemslist")]
    public enum ItemsList_Fields {
        
        /// <remarks/>
        No,
        
        /// <remarks/>
        Description,
        
        /// <remarks/>
        Description_2,
        
        /// <remarks/>
        TW_NSN_No_Cross_Reference_No,
        
        /// <remarks/>
        TWI_Item_Type,
        
        /// <remarks/>
        TWI_Update_Indicator_x003E_,
        
        /// <remarks/>
        Shelf_Life_Period,
        
        /// <remarks/>
        Addition_Status,
        
        /// <remarks/>
        TWI_FICCode,
        
        /// <remarks/>
        Created_From_Nonstock_Item,
        
        /// <remarks/>
        Substitutes_Exist,
        
        /// <remarks/>
        Stockkeeping_Unit_Exists,
        
        /// <remarks/>
        Assembly_BOM,
        
        /// <remarks/>
        Production_BOM_No,
        
        /// <remarks/>
        Routing_No,
        
        /// <remarks/>
        Base_Unit_of_Measure,
        
        /// <remarks/>
        Shelf_No,
        
        /// <remarks/>
        Costing_Method,
        
        /// <remarks/>
        Cost_is_Adjusted,
        
        /// <remarks/>
        Standard_Cost,
        
        /// <remarks/>
        TWI_Unit_Price,
        
        /// <remarks/>
        NAPA_Allowance_Pending_Approval,
        
        /// <remarks/>
        ROUND_Unit_Cost,
        
        /// <remarks/>
        Last_Direct_Cost,
        
        /// <remarks/>
        Price_Profit_Calculation,
        
        /// <remarks/>
        Net_Weight,
        
        /// <remarks/>
        Profit_Percent,
        
        /// <remarks/>
        Unit_Price,
        
        /// <remarks/>
        Inventory_Posting_Group,
        
        /// <remarks/>
        Gen_Prod_Posting_Group,
        
        /// <remarks/>
        VAT_Prod_Posting_Group,
        
        /// <remarks/>
        Item_Disc_Group,
        
        /// <remarks/>
        Vendor_No,
        
        /// <remarks/>
        Vendor_Name,
        
        /// <remarks/>
        Vendor_Item_No,
        
        /// <remarks/>
        Tariff_No,
        
        /// <remarks/>
        Search_Description,
        
        /// <remarks/>
        Overhead_Rate,
        
        /// <remarks/>
        Indirect_Cost_Percent,
        
        /// <remarks/>
        Item_Category_Code,
        
        /// <remarks/>
        Product_Group_Code,
        
        /// <remarks/>
        Blocked,
        
        /// <remarks/>
        Last_Date_Modified,
        
        /// <remarks/>
        Sales_Unit_of_Measure,
        
        /// <remarks/>
        Replenishment_System,
        
        /// <remarks/>
        Purch_Unit_of_Measure,
        
        /// <remarks/>
        Lead_Time_Calculation,
        
        /// <remarks/>
        Manufacturing_Policy,
        
        /// <remarks/>
        Flushing_Method,
        
        /// <remarks/>
        Manufacturer_Code,
        
        /// <remarks/>
        Brand_Code,
        
        /// <remarks/>
        Inventory,
        
        /// <remarks/>
        Aktobe_Stock,
        
        /// <remarks/>
        Aktau_Stock,
        
        /// <remarks/>
        Qty_on_Purch_Order,
        
        /// <remarks/>
        Qty_on_Sales_Order,
        
        /// <remarks/>
        Outstanding_Qty_on_I_B_TO_x0027_s,
        
        /// <remarks/>
        Outstanding_Qty_on_O_B_TO_x0027_s,
        
        /// <remarks/>
        Reserved_Qty_on_Inventory,
        
        /// <remarks/>
        Reserved_Qty_on_Purch_Orders,
        
        /// <remarks/>
        Reserved_Qty_on_Sales_Orders,
        
        /// <remarks/>
        Res_Qty_on_Outbound_Transfer,
        
        /// <remarks/>
        Res_Qty_on_Inbound_Transfer,
        
        /// <remarks/>
        History_at_Location,
        
        /// <remarks/>
        Purchase_blocked,
        
        /// <remarks/>
        Assembly_Policy,
        
        /// <remarks/>
        Qty_Sold,
        
        /// <remarks/>
        Item_Tracking_Code,
        
        /// <remarks/>
        Gross_Weight,
        
        /// <remarks/>
        Economic_Indicator,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ReadCompletedEventHandler(object sender, ReadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ItemsList Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ItemsList)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ReadByRecIdCompletedEventHandler(object sender, ReadByRecIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadByRecIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadByRecIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ItemsList Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ItemsList)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ReadMultipleCompletedEventHandler(object sender, ReadMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ItemsList[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ItemsList[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void IsUpdatedCompletedEventHandler(object sender, IsUpdatedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsUpdatedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsUpdatedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetRecIdFromKeyCompletedEventHandler(object sender, GetRecIdFromKeyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRecIdFromKeyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRecIdFromKeyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591